//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendingMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSentDetail
    {
        public int ID { get; set; }
        public int No_Of_Addresses { get; set; }
        public System.DateTime Date { get; set; }
        public string MailSent { get; set; }
    }
}
